/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
// Import the DBConnection class

/**
 *
 * @author Hp
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uname = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uname.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        uname.setToolTipText("");
        uname.setBorder(javax.swing.BorderFactory.createTitledBorder("USERNAME"));
        uname.setCaretColor(new java.awt.Color(204, 51, 255));
        uname.setDisabledTextColor(new java.awt.Color(204, 102, 255));
        uname.setOpaque(true);
        uname.setSelectionColor(new java.awt.Color(153, 102, 255));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 60));

        Login.setBackground(new java.awt.Color(204, 204, 255));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 130, 40));

        pass.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createTitledBorder("PASSWORD"));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 350, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/login.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 990, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

        String enteredUsername = uname.getText().trim();
        // Retrieving password as String from JPasswordField
        String enteredPassword = new String(pass.getPassword()).trim();

        // 1. Basic Field Validation
        if(enteredUsername.isEmpty() || enteredPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both username and password!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // NOTE FOR PROFESSIONAL DEVELOPMENT: 
        // In a production environment, you should NEVER store or check passwords in plaintext.
        // Always use a strong, one-way password hashing algorithm (like Argon2 or BCrypt) 
        // to securely store passwords and verify them.
        String sql = "SELECT username FROM users WHERE username = ? AND password = ?";

        // Establish connection using the DBConnection helper class
        try (
            Connection conn = DBConnection.getConnection(); // Use the connection utility
            // Prepare statement to prevent SQL Injection
            PreparedStatement pstmt = conn.prepareStatement(sql);
        ) {
            // Check if connection was successful before proceeding
            if (conn == null) {
                // DBConnection handles the specific error, just stop execution
                return; 
            }
            
            // Set the parameters safely
            pstmt.setString(1, enteredUsername);
            pstmt.setString(2, enteredPassword);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    // Successful Login: A matching record was found
                    JOptionPane.showMessageDialog(null, "Login Successful! Welcome, " + enteredUsername + ".");

                    // Open home frame (assuming 'home' is the name of your next JFrame class)
                    // You must ensure the 'home' class exists in your project.
                    home bahay = new home();
                    bahay.setVisible(true);

                    // Close the login frame
                    this.dispose();
                } else {
                    // Failed Login: No matching record found
                    JOptionPane.showMessageDialog(null, "Invalid Username or Password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                    pass.setText(""); // Clear password field
                }
            }
        } catch (SQLException ex) {
            // Handle query execution errors. Connection errors are primarily handled in DBConnection.
            JOptionPane.showMessageDialog(null, "Error during login check: " + ex.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}